### ISSUE TITLE
Create smoke/end-to-end test of infrastructure

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#125] opened 2020-12-10 21:17 UTC
We should introduce some test(s) to make sure we're able to change this infrastructure without worrying that it'll fall apart.

We might want to change this to run daily at some point, but for now we should just run it as part of every CI pipeline even if it is slow to work out any kinks and get to a stable test.

_Based on discussion with @imincik after https://github.com/linz/geospatial-data-lake/pull/103#issuecomment-742614457_

**Comment by imincik** [comment] 2020-12-11 10:00
Missed this ticket, moving it to Current tasks pipeline.

**Comment by imincik** [comment] 2020-12-21 20:13
Duplicate of #129

**Closed by imincik** 2020-12-21 20:13 UTC
